# See https://github.com/jderusse/docker-gitsplit
cache_dir: "/cache/gitsplit"

splits:
  - prefix: "a"
    target: "git@github.com:jderusse/test-split-a.git"
  - prefix: "b"
    target: "git@github.com:jderusse/test-split-b.git"

origins:
  - ^master$
  - ^\d+.\d+$
