# See https://github.com/jderusse/docker-gitsplit

# Path to a cache directory Used to speed up the split over time by reusing git's objects
cache_url: "/cache/gitsplit"
# cache_url: "file:///cache/gitsplit"
# cache_url: "https://${GH_TOKEN}@github.com/jderusse/test-split-cache.git"
# cache_url: "git@gitlab.com:jderusse/test-split-cache.git"

# Path to the repository to split (default = current path)
# project_url: /home/me/workspace/another_test-split
# project_url: ~/workspace/another_test-split
# project_url: ../another_test-split
# project_url: file://~/workspace/another_test-split
# project_url: "https://${GH_TOKEN}@github.com/jderusse/test-split.git"
# project_url: "git@gitlab.com:jderusse/test-split.git"

# List of splits.
splits:
  - prefix: "src/partA"
    target: "https://${GH_TOKEN}@github.com/jderusse/test-split-a.git"
  - prefix: "src/partB"
    target:
      # You can push the split to several repositories
      - "https://${GH_TOKEN}@github.com/jderusse/test-split-b.git"
      - "https://${GH_TOKEN}@github.com/jderusse/test-split-z.git"
  - prefix:
      # You can use several prefix in the split
      - "src/subTree/PartC:"
      - "src/subTree/PartZ:lib/z"
    target: "https://${GH_TOKEN}@github.com/jderusse/test-split-c.git"

# List of references to split (defined as regexp)
origins:
  - ^master$
  - ^develop$
  - ^feature/
  - ^v\d+\.\d+\.\d+$
